import React from 'react';
import ReactMarkdown from 'react-markdown';
import { Bot, Sparkles, BookOpen } from 'lucide-react';
import { Source } from '../types';
import SourceCard from './SourceCard';

interface AnswerSectionProps {
  content: string;
  sources: Source[];
}

const AnswerSection: React.FC<AnswerSectionProps> = ({ content, sources }) => {
  return (
    <div className="w-full max-w-4xl mx-auto animate-fadeIn">
      {/* Sources Carousel / Grid */}
      {sources.length > 0 && (
        <div className="mb-8">
          <div className="flex items-center gap-2 mb-4 text-slate-400 uppercase tracking-wider text-xs font-semibold">
            <BookOpen className="w-4 h-4" />
            <span>Sources</span>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {sources.slice(0, 4).map((source, idx) => (
              <SourceCard key={idx} source={source} index={idx} />
            ))}
          </div>
          {sources.length > 4 && (
             <div className="mt-2 text-right">
                <span className="text-xs text-slate-500 italic">and {sources.length - 4} more sources...</span>
             </div>
          )}
        </div>
      )}

      {/* Main Answer */}
      <div className="bg-surface/50 border border-slate-700/50 rounded-2xl p-6 md:p-8 shadow-xl backdrop-blur-sm">
        <div className="flex items-center gap-3 mb-6 border-b border-slate-700 pb-4">
          <div className="p-2 bg-gradient-to-br from-cyan-500 to-blue-600 rounded-lg shadow-lg">
            <Sparkles className="w-5 h-5 text-white" />
          </div>
          <h2 className="text-xl font-semibold text-white">AI Overview</h2>
        </div>
        
        <div className="markdown-content text-slate-300">
          <ReactMarkdown
            components={{
              // Custom link renderer to make links open in new tab and look styled
              a: ({ node, ...props }) => (
                <a 
                  {...props} 
                  target="_blank" 
                  rel="noopener noreferrer" 
                  className="text-cyan-400 hover:text-cyan-300 underline decoration-cyan-400/30 hover:decoration-cyan-300 transition-all" 
                />
              )
            }}
          >
            {content}
          </ReactMarkdown>
        </div>

        <div className="mt-8 pt-4 border-t border-slate-700 flex justify-between items-center text-xs text-slate-500">
           <div className="flex items-center gap-2">
             <Bot className="w-4 h-4" />
             <span>Generated by Gemini 2.5 Flash</span>
           </div>
           <div>
             <span>Nexus Deep Search</span>
           </div>
        </div>
      </div>
    </div>
  );
};

export default AnswerSection;